### ISSUE TITLE
Vacations days are returned in hours

### ISSUE THREAD

**Issue by phadej** [planmill/api#12]
And the problem is that usually one want to display that information in days. Where from one can find how much hours in a day to calculate actual vacation days.

Currently I use `defaultDailyWorktime` from the user's capacity calendar, but it doesn't seem to be correct?

**Comment by petrukhnov-planmill** [comment]
Capacity are in minutes. E.g. for Finland: 450 (7.5*60)
daysRemaining is also in minutes: 13500 (30*7.5*60)

You could use: 
/api/1.5/users/[userId]/vacations/[vacationId]
It have "annualHoliday": 30, (in days)

**Comment by phadej** [comment]
Haven't time to check this. We found that capacity is minutes and days are calculated for everyone with 7.5 hour "work days" (though some work 8/6/x hours per day). Which is a bit undirect, but seems to work.
