### ISSUE TITLE
Api get invoices, can't reference to project

### ISSUE THREAD

**Issue by chenmengyang** [planmill/api#18]
Hi, I think the invoices API has a problem, or maybe I use it in wrong way.

I try to fetch invoices using API 1.5, but there is no project or task/assignment fields in returned invoices, how can I know which project a invoice belongs to ? Can anyone please help, thanks in advance.

**Comment by grahamdaw** [comment]
From checking the various endpoints so far, it seems no objects specify a relationship to invoices & invoices have no relationships returned to projects/sales orders etc.
With the API, is there any way to get a relationship from invoices to Sales Orders/Projects?

**Comment by corvuscornix** [comment]
Hey,

and sorry for no one replying for so long. We haven't had anyone paying attention to these issues for a while.

It's true that there doesn't seem to be connecting information available between these objects currently. Is this information still relevant?

As invoice may be related to multiple salesorders and projects at the same time (= combined invoices) this information would most likely require developing a totally new endpoint /invoices/12345/items which would list the information per invoice item along with the requested salesorder and project id.
