### ISSUE TITLE
Unable to update Opportunities

### ISSUE THREAD

**Issue by miekari** [planmill/api#20]
Hi,

I have created Opportunity via 1.5 api with example payload:

{
  "id": 12345,
  "reason": 0,
  "request": 1234,
  "subject": "Opportunity test",
  "probability": 10,
  "description": "",
  "source": 0,
  "priority": 2,
  "type": 0,
  "stage": 10,
  "competitor": -1,
  "partnerContact": null,
  "responsible": 2834513,
  "contact": 2834513,
  "nextStep": 0,
  "closed": "2015-04-30T00:00:00.000+0300",
  "status": 0
}

rest url used:
online.planmill.com/{customer_instance}/api/1.5/opportunities

creation goes fine but when I try to update Opportunity with received id set as id value to payload Opportunity is created again not updated. API description says:

_Add a new opportunity to PlanMill or update existing (if id is given). See opportunities/meta for list of columns and formats._

id is given but update does not happen. My question is this bug or I am doing something wrong. Http request method used is POST

**Comment by miekari** [comment]
Hi @corvuscornix and thank you for the information. Now I have another problem;  I would like to get information about Opportunity fields via "online.planmill.com/{customer_instance}/api/1.5/opportunities/meta" endpoint but I am getting  error response: Requested resource could not be mapped to an API endpoint, check the documentation. 

what could be the problem?

""

**Comment by corvuscornix** [comment]
Hey @miekari that is the correct endpoint and it should work. Could you contact PlanMill support so we can investigate further whether it's something in your PlanMill instance?
