### ISSUE TITLE
timereports post has incorrect input field for project id

### ISSUE THREAD

**Issue by leomelin** [planmill/api#23]
I noticed that at some point in history, this api (https://developers.planmill.com/api/#timereports_post) has started to fail when field `project` is used in json body as documented. It responds with validation error `PMVProject.Id` is a required field. The api works if the `project` field is renamed to `PMVProject.Id` but this really feels like a bug. For some reason mapping project as PMVProject.Id is not working anymore in the api

**Comment by gavinvandok** [comment]
We have tried to reproduce the error without success but the main issues for the timereports POST is that you should not be using project anyway. That field is for GET. We will update the docs with a useful example there. To create a useful timereport please note that only person, start, amount and task are needed (plus comment of course if commenting is required by project). Thanks for the feedback and we hope you can solve your issues with this advice.

**Comment by leomelin** [comment]
Thanks @gavinvandok, this was useful information! The API docs are misleading here - The example describes many irrelevant fields then. I hope you can update the docs with better example 👍

**Comment by leomelin** [comment]
Actually now I tried to update the project with the time reporting feature by those terms you explained and it doesn't work...

endpoint: `POST to https://online.planmill.com/OUR_INSTANCE/api/1.5/timereports`
payload: 
```json
{  
   "headers":{  
      "cache-control":"no-cache",
      "Content-type":"application/json; charset=utf-8",
      "authorization":"Bearer XXXXXXXXXXXX"
   },
   "json":true,
   "body":{  
      "amount":450,
      "start":"2018-12-07T08:00:00.000+0200",
      "task":670473,
      "person":250847,
      "comment":"Testing"
   }
}
```
Reponse:
Status 400 
```json
{"code":"00018","message":"Validation failed","fields":{"PMVProject.Id":"Pakollinen kenttä"}}
```

**Comment by gavinvandok** [comment]
Where are you from  - what instance are you testing in? With a person with an assignment to a valid task, submitting in our trial instance I just tested and was able to create an time report ok with exactly those fields.
