### ISSUE TITLE
Is it possible to use 1.5 API to import Expenses?

### ISSUE THREAD

**Issue by lkallioniemi** [planmill/api#5]
From API documentation, it appears that all expense endpoints to are read only. Is it possible to use api to import Expences? I see that creating project purchases is possible, but that doesn't contain the same data as expense can

**Comment by pm-pasi-harme** [comment]
We do not currently support creating or modifying expenses via the 1.5 API. We have plans for improving the Expense and Journey modules which is expected to be done during Q1 2017. The endpoints for creating expenses will be available then.

**Comment by pm-pasi-harme** [comment]
Reopened for visibility

**Comment by gavinvandok** [comment]
/expenses POST has been available since 24/08/2017
