### ISSUE TITLE
The /reports GET APIs do not work with reports that contain "/" character in the report name

### ISSUE THREAD

**Issue by skunkbadger** [planmill/api#6]
In the 23/03/2017 Planmill update, a few reports were renamed to contain "/"-characters in their names. Release notes here as a reference about the change: https://help.planmill.com/help/release-notes/

The new report names were:
Invoicing by customer /  sales account / month
Invoicing by sales account / customer / month

* Please also note that the first report name has two spaces before the word sales.

The problem with this new naming is that these reports can no longer be accessed using the /reports/{reportName} or /reports/{reportName}/meta APIs. URL encoding the problematic character in the request does not help and the API always responds with status 400.

**Comment by gallobello** [comment]
We have reverted the changes (for English names) and they will be in production tomorrow 23.3.2017. They are now returned to:
- Invoicing monthly summary by customer 
- Invoicing monthly summary by sales account   

Reports API will be improved for better identifiers in the future.  
Best Regards
